import type { Metadata } from 'next'
import { Providers } from '@/providers'
import { Aboreto, Roboto } from 'next/font/google'

const aboreto = Aboreto({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-aboreto',
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto',
})

export const metadata: Metadata = {
  title: 'Gabriel Brustolin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${aboreto.variable} ${roboto.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
